[package]
name = "bhwi-e2e-hwi-parity"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license-file.workspace = true

[dependencies]
anyhow.workspace = true
bhwi = { workspace = true, features = ["keepkey"] }
bitcoin = { workspace = true, features = ["base64"] }
serde_json.workspace = true

bhwi-e2e-trezor = { path = "../trezor" }
bhwi-e2e-keepkey = { path = "../keepkey" }
tokio = { workspace = true, features = ["net", "rt", "time"] }
