[package]
name = "bhwi-async"
version = "0.0.1"
edition = "2024"
authors.workspace = true
repository = "https://github.com/wizardsardine/bhwi"
license-file.workspace = true
keywords = ["bitcoin",  "miniscript"]
description = "development kit"
readme = "README.md"
documentation = "https://docs.rs/bhwi-async"
homepage = "https://wizardsardine.github.io/bhwi/"

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-linux-gnu"
targets = []

[features]
default = ["bitbox", "coldcard", "jade", "keepkey", "ledger", "specter", "trezor"]
bitbox = ["bhwi/bitbox"]
coldcard = ["bhwi/coldcard"]
jade = ["bhwi/jade", "serde_cbor"]
keepkey = ["bhwi/keepkey"]
ledger = ["bhwi/ledger"]
specter = ["bhwi/specter"]
trezor = ["bhwi/trezor"]

[dependencies]
async-trait.workspace = true
bhwi.workspace = true
serde_cbor = { workspace = true, optional = true }
thiserror.workspace = true

byteorder = "1.5"

[dev-dependencies]
futures.workspace = true
