#!/usr/bin/env python3
"""Stage an mdBook from the root README and automatically discovered guides."""

import os
from pathlib import Path
import re
import shutil
import string
import sys


API_REFERENCE = """# API reference

## Released APIs (docs.rs)

These are the latest published releases. They may lag `main` and have not been
regenerated by this Pages build. The new crate overviews apply to future releases.

- [bhwi](https://docs.rs/bhwi/latest/bhwi/)
- [bhwi-async](https://docs.rs/bhwi-async/latest/bhwi_async/)

The native transport (`bhwi-async-transport`), CLI (`bhwi-cli`), and browser
(`bhwi-wasm`) crates are not yet published on crates.io.

## Current development APIs (main)

These references are built from `main` alongside this book. Native and browser
references are separate target builds, with their own source and search assets.

- [bhwi (native)](api/native/bhwi/index.html)
- [bhwi-async (native)](api/native/bhwi_async/index.html)
- [bhwi-async-transport (native)](api/native/bhwi_async_transport/index.html)
- [bhwi-cli (native)](api/native/bhwi_cli/index.html)
- [bhwi-wasm (browser)](api/wasm/bhwi_wasm/index.html)

The historical examples in [VISION](docs/VISION.md) are conceptual, not tested
current-API tutorials.

[Return to the browser demo](../)
"""


def chapter_title(text, path):
    for line in text.splitlines():
        if line.strip():
            heading = re.fullmatch(r" {0,3}#(?:[ \t]+(.*))?", line)
            if heading:
                title = heading.group(1) or ""
                return re.sub(r"(?:^|[ \t]+)#+[ \t]*$", "", title).strip()
            break
    return path.stem


def summary_entry(title, path):
    if any(character in path for character in "\r\n<>#?%\\&"):
        raise ValueError(f"Unsupported chapter path: {path!r}")
    label = "".join(
        "\\" + character if character in string.punctuation else character
        for character in title
    )
    return f"- [{label}](<{path}>)\n"


def copy_guides(source, destination, chapters):
    destination.mkdir()
    with os.scandir(source) as entries:
        for entry in entries:
            if entry.name.startswith(".") or entry.is_symlink():
                continue
            source_path = Path(entry.path)
            destination_path = destination / entry.name
            if entry.is_dir(follow_symlinks=False):
                copy_guides(source_path, destination_path, chapters)
            elif entry.is_file(follow_symlinks=False):
                if entry.name.lower() == "summary.md":
                    continue
                shutil.copyfile(source_path, destination_path)
                if source_path.suffix == ".md":
                    chapters.append(destination_path)


def build_book(source_root, book_dir):
    book_dir.mkdir()
    shutil.copyfile(source_root / "nix/book.toml", book_dir / "book.toml")
    source = book_dir / "src"
    source.mkdir()
    introduction = (source_root / "README.md").read_text(encoding="utf-8")
    (source / "README.md").write_text(
        "> This book tracks development on main. For released and current "
        "development APIs, see [API reference](API.md).\n\n" + introduction,
        encoding="utf-8",
    )
    guides = []
    docs = source_root / "docs"
    if docs.is_symlink():
        raise ValueError(f"Documentation directory must not be a symlink: {docs}")
    copy_guides(docs, source / "docs", guides)
    summary = "# Summary\n\n" + summary_entry(
        chapter_title(introduction, Path("README.md")), "README.md"
    )
    for guide in sorted(guides, key=lambda path: path.relative_to(source).as_posix()):
        summary += summary_entry(
            chapter_title(guide.read_text(encoding="utf-8"), guide),
            guide.relative_to(source).as_posix(),
        )
    summary += summary_entry("API reference", "API.md")
    (source / "SUMMARY.md").write_text(summary, encoding="utf-8")
    (source / "API.md").write_text(API_REFERENCE, encoding="utf-8")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("Usage: build-docs.py SOURCE_ROOT BOOK_DIR")
    build_book(Path(sys.argv[1]), Path(sys.argv[2]))
